# Generated by Django 5.0.3 on 2024-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bill', models.IntegerField()),
                ('title', models.TextField()),
                ('primary_sponsor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Legislators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legislator', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vote', models.IntegerField()),
                ('id_bill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotesResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_results', models.IntegerField()),
                ('id_legislator', models.IntegerField()),
                ('id_vote', models.IntegerField()),
                ('vote_type', models.IntegerField()),
            ],
        ),
    ]
